apiVersion: v1
kind: PersistentVolume
metadata:
  name: fastapi-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fastapi-storage
  hostPath:
    path: /mnt/data/fastapi

