apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pgadmin-cert
  namespace: default
spec:
  secretName: pgadmin-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: pgadmin.tanoh.dns-dynamic.net
  dnsNames:
  - pgadmin.tanoh.dns-dynamic.net
