apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: fastapi-cert
  namespace: default
spec:
  secretName: fastapi-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: fastapi.tanoh.dns-dynamic.net
  dnsNames:
  - fastapi.tanoh.dns-dynamic.net
