---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  storageClassName: postgres-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
